name: flutter_starter_tempalte
description: "Flutter starter template"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3
  auto_route: ^5.0.1
  flutter_platform_widgets: ^2.0.0
  material_color_generator: ^1.1.0
  slang: ^3.0.0
  slang_flutter: ^3.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  http: ^0.13.5
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  mockito: ^5.3.2
  json_serializable: ^6.4.0
  slang_build_runner: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - .env
