name: flutter_starter_tempalte
description: "Flutter starter template"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  injectable: ^1.5.3
  auto_route: ^4.2.1
  flutter_platform_widgets: ^2.0.0
  material_color_generator: ^1.1.0
  slang: ^2.7.0
  slang_flutter: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  auto_route_generator: ^4.2.1
  slang_build_runner: ^2.7.0

flutter:
  uses-material-design: true
  assets:
   - .env
